export const metadata = {
  title: "Decommissioning",
  description: "Generated by create next app",
};

export default function DecommissioningLayout({ children }) {
  return <div>{children}</div>;
}
